[package]
description = "Captures minidumps in a child process"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "minidumper-child"
readme = "README.md"
repository = "https://github.com/timfish/minidumper-child"
version = "0.5.0"

[dependencies]
crash-handler = "0.8"
minidumper = "0.11"
thiserror = "2"
uuid = {version = "1", features = ["v4"]}

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
sadness-generator = "0.7"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
